// <auto-generated />
using System;
using GermanBocanegra.Test.Infodesign.Infrastructure.Adapters.Output.ORMDefinitions.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GermanBocanegra.Test.Infodesign.Infrastructure.Migrations
{
    [DbContext(typeof(MainEntityFrameworkContext))]
    partial class MainEntityFrameworkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GermanBocanegra.Test.Infodesign.Domain.Models.Entities.EnergyMetrics.EnergyConsumptionEntity", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<int>("Commercial")
                        .HasColumnType("int");

                    b.Property<int>("Industrial")
                        .HasColumnType("int");

                    b.Property<int>("Residential")
                        .HasColumnType("int");

                    b.Property<int>("ServiceLineID")
                        .HasColumnType("int");

                    b.Property<int>("TimeSegmentID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TimeSegmentID");

                    b.HasIndex("ServiceLineID", "TimeSegmentID")
                        .IsUnique();

                    b.ToTable("EnergyConsumption", (string)null);
                });

            modelBuilder.Entity("GermanBocanegra.Test.Infodesign.Domain.Models.Entities.EnergyMetrics.EnergyCostEntity", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<decimal>("Commercial")
                        .HasColumnType("decimal(18,10)");

                    b.Property<decimal>("Industrial")
                        .HasColumnType("decimal(18,10)");

                    b.Property<decimal>("Residential")
                        .HasColumnType("decimal(18,10)");

                    b.Property<int>("ServiceLineID")
                        .HasColumnType("int");

                    b.Property<int>("TimeSegmentID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TimeSegmentID");

                    b.HasIndex("ServiceLineID", "TimeSegmentID")
                        .IsUnique();

                    b.ToTable("EnergyCost", (string)null);
                });

            modelBuilder.Entity("GermanBocanegra.Test.Infodesign.Domain.Models.Entities.EnergyMetrics.EnergyLossEntity", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<decimal>("Commercial")
                        .HasColumnType("decimal(11,10)");

                    b.Property<decimal>("Industrial")
                        .HasColumnType("decimal(11,10)");

                    b.Property<decimal>("Residential")
                        .HasColumnType("decimal(11,10)");

                    b.Property<int>("ServiceLineID")
                        .HasColumnType("int");

                    b.Property<int>("TimeSegmentID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TimeSegmentID");

                    b.HasIndex("ServiceLineID", "TimeSegmentID")
                        .IsUnique();

                    b.ToTable("EnergyLoss", (string)null);
                });

            modelBuilder.Entity("GermanBocanegra.Test.Infodesign.Domain.Models.Entities.MeasurementSegments.TimeSegmentEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateOnly>("TimeSegmentDate")
                        .HasColumnType("date");

                    b.HasKey("ID");

                    b.ToTable("TimeSegment", (string)null);
                });

            modelBuilder.Entity("GermanBocanegra.Test.Infodesign.Domain.Models.Entities.ServiceLines.ServiceLineEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ServiceLineName")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("ID");

                    b.ToTable("ServiceLine", (string)null);
                });

            modelBuilder.Entity("GermanBocanegra.Test.Infodesign.Domain.Models.Entities.EnergyMetrics.EnergyConsumptionEntity", b =>
                {
                    b.HasOne("GermanBocanegra.Test.Infodesign.Domain.Models.Entities.ServiceLines.ServiceLineEntity", "ServiceLine")
                        .WithMany("EnergyConsumptions")
                        .HasForeignKey("ServiceLineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GermanBocanegra.Test.Infodesign.Domain.Models.Entities.MeasurementSegments.TimeSegmentEntity", "TimeSegment")
                        .WithMany("EnergyConsumptions")
                        .HasForeignKey("TimeSegmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceLine");

                    b.Navigation("TimeSegment");
                });

            modelBuilder.Entity("GermanBocanegra.Test.Infodesign.Domain.Models.Entities.EnergyMetrics.EnergyCostEntity", b =>
                {
                    b.HasOne("GermanBocanegra.Test.Infodesign.Domain.Models.Entities.ServiceLines.ServiceLineEntity", "ServiceLine")
                        .WithMany("EnergyCosts")
                        .HasForeignKey("ServiceLineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GermanBocanegra.Test.Infodesign.Domain.Models.Entities.MeasurementSegments.TimeSegmentEntity", "TimeSegment")
                        .WithMany("EnergyCosts")
                        .HasForeignKey("TimeSegmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceLine");

                    b.Navigation("TimeSegment");
                });

            modelBuilder.Entity("GermanBocanegra.Test.Infodesign.Domain.Models.Entities.EnergyMetrics.EnergyLossEntity", b =>
                {
                    b.HasOne("GermanBocanegra.Test.Infodesign.Domain.Models.Entities.ServiceLines.ServiceLineEntity", "ServiceLine")
                        .WithMany("EnergyLosses")
                        .HasForeignKey("ServiceLineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GermanBocanegra.Test.Infodesign.Domain.Models.Entities.MeasurementSegments.TimeSegmentEntity", "TimeSegment")
                        .WithMany("EnergyLosses")
                        .HasForeignKey("TimeSegmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceLine");

                    b.Navigation("TimeSegment");
                });

            modelBuilder.Entity("GermanBocanegra.Test.Infodesign.Domain.Models.Entities.MeasurementSegments.TimeSegmentEntity", b =>
                {
                    b.Navigation("EnergyConsumptions");

                    b.Navigation("EnergyCosts");

                    b.Navigation("EnergyLosses");
                });

            modelBuilder.Entity("GermanBocanegra.Test.Infodesign.Domain.Models.Entities.ServiceLines.ServiceLineEntity", b =>
                {
                    b.Navigation("EnergyConsumptions");

                    b.Navigation("EnergyCosts");

                    b.Navigation("EnergyLosses");
                });
#pragma warning restore 612, 618
        }
    }
}
